language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "2.7"

install:
  - pip install -U .

script:
  - python setup.py test

notifications:
  email:
    - noah.hoffman@gmail.com
